# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:23
# Modified by Louis Wust on 2017-02-21 12:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
            migrations.CreateModel(
                    name='Application',
                    fields=[
                            ('id',
                             models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                             )),
                            ('submitted', models.BooleanField(default=False)),
                            ('created_at', models.DateTimeField()),
                            ('updated_at', models.DateTimeField()),
                            ('due_at', models.DateTimeField()),
                            ('name',
                             models.CharField(
                                    blank=True,
                                    max_length=255,
                                    verbose_name='full name'
                             )),
                            ('address',
                             models.TextField(
                                    blank=True,
                                    verbose_name='permanent mailing address'
                             )),
                            ('phone',
                             phonenumber_field.modelfields.PhoneNumberField(
                                    blank=True,
                                    help_text='Cell phone is acceptable',
                                    max_length=128,
                                    verbose_name='primary phone number'
                             )),
                            ('psu_email',
                             models.EmailField(
                                    blank=True,
                                    help_text='This is your psu.edu e-mail',
                                    max_length=254,
                                    validators=[django.core.validators.RegexValidator('^(?:[^@]+@psu.edu)?$')],
                                    verbose_name='university e-mail address'
                             )),
                            ('preferred_email',
                             models.EmailField(
                                    blank=True,
                                    max_length=254,
                                    verbose_name='preferred e-mail address'
                             )),
                            ('psu_id',
                             models.CharField(
                                    blank=True,
                                    help_text='Nine digits: 9xxxxxxxx',
                                    max_length=9,
                                    validators=[django.core.validators.RegexValidator('^(?:9\\d{8})?$')],
                                    verbose_name='university ID number'
                             )),
                            ('date_initiated',
                             models.DateField(
                                    blank=True,
                                    null=True,
                                    verbose_name='date of initiation'
                             )),
                            ('date_graduating',
                             models.DateField(
                                    blank=True,
                                    null=True,
                                    verbose_name='planned graduation date'
                             )),
                            ('cumulative_gpa',
                             models.DecimalField(
                                    blank=True,
                                    decimal_places=2,
                                    max_digits=3,
                                    null=True,
                                    verbose_name='cumulative GPA'
                             )),
                            ('semester_gpa',
                             models.DecimalField(
                                    blank=True,
                                    decimal_places=2,
                                    max_digits=3,
                                    null=True,
                                    verbose_name='last semester GPA'
                             )),
                            ('in_state_tuition',
                             models.NullBooleanField(
                                    help_text='Do you pay the reduced tuition rate for PA residents?',
                                    verbose_name='in-state tuition'
                             )),
                    ],
            ),
            migrations.CreateModel(
                    name='AdditionalRemark',
                    fields=[
                            ('id',
                             models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                             )),
                            ('remark_type', models.SlugField()),
                            ('remark_content',
                             models.TextField(
                                    verbose_name='additional remarks'
                             )),
                            ('application',
                             models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='freemoney.Application'
                             ))
                    ],
            ),
            migrations.CreateModel(
                    name='EssayPrompt',
                    fields=[
                            ('id',
                             models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                             )),
                            ('persistent_tag', models.SlugField(blank=True)),
                            ('created_at', models.DateTimeField()),
                            ('prompt', models.TextField()),
                    ],
                    options={'abstract': False},
            ),
            migrations.CreateModel(
                    name='Essay',
                    fields=[
                            ('id',
                             models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                             )),
                            ('text', models.TextField()),
                            ('application',
                             models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='freemoney.Application'
                             )),
                            ('prompt',
                             models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='freemoney.EssayPrompt'
                             )),
                    ],
            ),
            migrations.CreateModel(
                    name='FinancialAid',
                    fields=[
                            ('id',
                             models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                             )),
                            ('aid_type',
                             models.CharField(
                                    blank=True,
                                    max_length=50,
                                    verbose_name='type'
                             )),
                            ('source',
                             models.CharField(
                                    blank=True,
                                    help_text='Full name of the fund, organization, sponsor, etc.',
                                    max_length=255,
                                    verbose_name='source'
                             )),
                            ('amount_per_year',
                             models.DecimalField(
                                    blank=True,
                                    decimal_places=2,
                                    max_digits=7,
                                    null=True
                             )),
                            ('start_date',
                             models.DateField(
                                    blank=True,
                                    null=True
                             )),
                            ('end_date',
                             models.DateField(
                                    blank=True,
                                    null=True
                             )),
                            ('application',
                             models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='freemoney.Application'
                             )),
                    ],
            ),
            migrations.CreateModel(
                    name='ScholarshipAward',
                    fields=[
                            ('id',
                             models.AutoField(
                                    auto_created=True,
                                    primary_key=True,
                                    serialize=False,
                                    verbose_name='ID'
                             )),
                            ('persistent_tag', models.SlugField(blank=True)),
                            ('created_at', models.DateTimeField()),
                            ('name', models.CharField(max_length=255)),
                            ('description', models.TextField()),
                            ('application_set', models.ManyToManyField(
                                    to='freemoney.Application'
                             )),
                    ],
                    options={'abstract': False},
            ),
            migrations.CreateModel(
                    name='ApplicantProfile',
                    fields=[
                            ('user',
                             models.OneToOneField(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    primary_key=True,
                                    serialize=False,
                                    to=settings.AUTH_USER_MODEL
                             )),
                            ('must_change_password', models.BooleanField()),
                    ],
            ),
            migrations.CreateModel(
                    name='PeerProfile',
                    fields=[
                            ('user',
                             models.OneToOneField(
                                    on_delete=django.db.models.deletion.CASCADE,
                                    primary_key=True,
                                    serialize=False,
                                    to=settings.AUTH_USER_MODEL
                             )),
                            ('active', models.BooleanField()),
                            ('display_name', models.CharField(max_length=255)),
                    ],
            ),
            migrations.AddField(
                    model_name='EssayPrompt',
                    name='application_set',
                    field=models.ManyToManyField(
                            through='freemoney.Essay',
                            to='freemoney.Application'),
            ),
            migrations.AddField(
                    model_name='EssayPrompt',
                    name='previous_version',
                    field=models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            to='freemoney.EssayPrompt'),
            ),
            migrations.AddField(
                    model_name='ScholarshipAward',
                    name='previous_version',
                    field=models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            to='freemoney.ScholarshipAward'),
            ),
            migrations.AddField(
                    model_name='Application',
                    name='applicant',
                    field=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to='freemoney.ApplicantProfile'),
            ),
    ]
