# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import freemoney.models.semester


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('must_change_password', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('address', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('psu_email', models.TextField(blank=True)),
                ('preferred_email', models.TextField(blank=True)),
                ('psu_id', models.TextField(blank=True)),
                ('outside_pa', models.BooleanField(default=False)),
                ('semester_initiated', freemoney.models.semester.SemesterField(blank=True, null=True)),
                ('semester_graduating', freemoney.models.semester.SemesterField(blank=True, null=True)),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('semester_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('in_state_tuition', models.BooleanField(default=False)),
                ('additional_remarks', models.TextField(blank=True)),
                ('submitted', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.ApplicantProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('application_set', models.ManyToManyField(to='freemoney.Application')),
                ('previous_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freemoney.Award')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.Application')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.ApplicantProfile')),
            ],
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freemoney.Application'),
        ),
    ]
