# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:53
from __future__ import unicode_literals

from django.db import migrations


def insert_awards(apps, schema_editor_):
    Award = apps.get_model('freemoney', 'Award')
    Award.objects.create(identifier='ean_hong',
                         name='Ean H. C. Hong Memorial Scholarship',
                         description="""
Honoring Ean Heng Cheung Hong ps94, rewards academics, service, peer feedback.
Applicants will be required to answer additional essay questions. Two awards
are available this Spring, each valued at $4,000. Strong preference will be
given to applicants who have not already received this award. Important note:
the Ean H. C. Hong Memorial Scholarship is awarded in the semester
*following*, which means you will need to be an active member during the Fall
of 2016 to be eligible for this award.
""".strip().replace('\n', ''))
    Award.objects.create(identifier='ambassador',
                         name='Ted McLaughlin Triangle Ambassador Award',
                         description="""
Honoring Ted McLaughlin ps57, rewards academics and involvement in activities.
Applicants will be required to answer additional essay questions. One award is
available this Spring, valued at $1,500. Strong preference will be given to
applicants who have not already received this award. Being a TFAEF award, this
is unavailable to graduating seniors.
""".strip().replace('\n', ''))
    Award.objects.create(identifier='excellence',
                         name='Triangle Academic Excellence Award',
                         description="""
Rewards GPA, claimable only once per brother. Reward amount is "tiered" based
on cumulative GPA ($250 for 3.33-3.66, $500 for 3.67-4.00) -- there is some
incentive to wait if you believe your grades will improve. No essay questions.
Individuals who already received this award are not eligible to receive it
again. Being a TFAEF award, this is unavailable to graduating seniors.
""".strip().replace('\n', ''))
    Award.objects.create(identifier='pledge',
                         name='Studious Pledge Award',
                         description="""
Rewards GPA, claimable only by NIBs. If you pledged last semester and earned a
3.50 GPA cumulative or higher, definitely apply for this award. No essay
questions. Being a TFAEF award, this is unavailable to graduating seniors.
""".strip().replace('\n', ''))
    Award.objects.create(identifier='navy_marine',
                         name='Studious Pledge Award',
                         description="""
Shared amongst all active, reservist, and honorably discharged brothers in the
US Navy or Marine Corps. If you meet the criteria, apply. No essay questions.
Individuals may receive this award as often as it is offered. Being a TFAEF
award, this is unavailable to graduating seniors.
""".strip().replace('\n', ''))
    Award.objects.create(identifier='joe_conway',
                         name='Joe Conway Award',
                         description="""
Special award, shared amongst all Engineering Science and Engineering
Mechanics majors. If you meet the criteria, apply. No essay questions.
Individuals may receive this award as often as it is offered. Being a TFAEF
award, this is unavailable to graduating seniors.
""".strip().replace('\n', ''))
    Award.objects.create(identifier='giff_albright',
                         name='Giff Albright Architectural Engineering Award',
                         description="""placeholder""")
    Award.objects.create(identifier='dan_summers',
                         name='Daniel E. Summers Memorial Scholarship',
                         description="""placeholder""")

class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_awards)
    ]
