# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.Application')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.PeerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='reviewedpeer_set',
            field=models.ManyToManyField(through='freemoney.PeerFeedback', to='freemoney.PeerProfile'),
        ),
    ]
