# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import freemoney.models.semester


class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='additional_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cumulative_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferred_email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='psu_email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='psu_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester_graduating',
            field=freemoney.models.semester.SemesterField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester_initiated',
            field=freemoney.models.semester.SemesterField(blank=True, null=True),
        ),
    ]
