# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:53
from __future__ import unicode_literals

from django.db import migrations


def insert_awards(apps, schema_editor_):
    Award = apps.get_model('freemoney', 'Award')
    Award.objects.create(identifier='ean_hong',
                         name='Ean H. C. Hong Memorial Scholarship',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_ean_hong">chapter
website</a>.</p>
<p>In memory of Ean Heng Cheung Hong. Rewards academics, service, peer
feedback. 2x Fall and 2x Spring, &dollar;4,000 per awardee.</p>
<p>Applicants are graded on an array of criteria.  Strong preference will be
given to applicants who have not already received this award.</p>
<p><em>Additional information and essays are required</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='ambassador',
                         name='Ted McLaughlin Triangle Ambassador Award',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_ted_mclaughlin">chapter
website</a>.</p>
<p>Honoring Ted McLaughlin ps57. rewards academics and involvement in
activities. 1x Spring, &dollar;1,500 per awardee.</p>
<p>Applicants are graded on an array of criteria.</p>
<p><em>Additional information and essays are required</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='excellence',
                         name='Triangle Academic Excellence Award',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_excellence">chapter
website</a>.</p>
<p>Rewards GPA, claimable only once per brother.  If you already claimed it
once, you cannot receive it again. Reward amount is "tiered" based on
cumulative GPA (&dollar;250 for 3.33-3.66, &dollar;500 for 3.67-4.00).</p>
<p><em>No additional information or essays are required</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='pledge',
                         name='Studious Pledge Award',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_pledge">chapter
website</a>.</p>
<p>Rewards GPA, claimable only by NIBs. If you pledged last semester and
earned a 3.50 GPA cumulative or higher, you will automatically win this award,
which is equivalent to the value of your pledge fee (&dollar;350 as of this
writing).</p>
<p><em>No additional information or essays are required</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='navy_marine',
                         name='Navy / Marine Corps Service Scholarship',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_navy_marine">chapter
website</a>.</p>
<p>Award is automatically shared amongst all active, reservist, and honorably
discharged brothers in the US Navy or Marine Corps. 1x Spring, &dollar;500
split among winners.</p>
<p><em>Some additional information is required, but no essays</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='joe_conway',
                         name='Joe Conway Award',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_joe_conway">chapter
website</a>.</p>
<p>Honoring Dr. Joseph Conway, this award is shared amongst all qualified
Engineering Science majors and anyone working towards an Engineering Mechanics
minor. 1x Spring &dollar;500.
<p><em>Some additional information is required, but no essays</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='giff_albright',
                         name='Giff Albright Architectural Engineering Award',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_giff_albright">chapter
website</a>.</p>
<p>Honoring Giff Albright's continuing achievements, rewards proficient and
involved Architectural Engineering majors. 1x Spring &dollar;1,000.</p>
<p>Each applicant is required to meet with a Department of Architectural
Engineering faculty member (either active or emeritus).</p>
<p><em>Additional information and essays are required</em>.</p>
""".strip().replace('\n', ' '))
    Award.objects.create(identifier='daniel_summers',
                         name='Daniel E. Summers Memorial Scholarship',
                         description="""
<p>Complete information on all awards is available on the <a
href="http://psutriangle.org/information/scholarships/#schp_daniel_summers">chapter
website</a>.</p>
<p>Honoring Br. Daniel Summers, rewards loyalty, advocacy, and humility. 1x
Spring &dollar;500.</p>
<p>Applicants are graded on an array of criteria, including service to the
fraternity and bonds of friendship. <em>Additional information and a short essay are required</em>.</p>
""".strip().replace('\n', ' '))

class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_awards)
    ]
