# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0002_award_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.SlugField(blank=True)),
                ('provider', models.TextField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('installment_frequency', models.TextField(blank=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.Application')),
            ],
        ),
    ]
