# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0004_finished_date_to_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.Application')),
            ],
        ),
        migrations.CreateModel(
            name='EssayPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField()),
                ('prompt', models.TextField()),
                ('word_limit', models.IntegerField()),
                ('application_set', models.ManyToManyField(through='freemoney.Essay', to='freemoney.Application')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freemoney.EssayPrompt')),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freemoney.EssayPrompt'),
        ),
    ]
