# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:53
from __future__ import unicode_literals

from django.db import migrations


def insert_essays(apps, schema_editor_):
    EssayPrompt = apps.get_model('freemoney', 'EssayPrompt')
    EssayPrompt.objects.create(
            identifier='newmember_involvement_previous',
            word_limit=500,
            prompt="""
As a recently-initiated member of Triangle, you bring a fresh perspective to
the Fraternity. What activities have you participated in prior to becoming a
member? This could include work history, research activities, professional
societies, publications/awards, mentorship/tutoring, clubs related to
engineering, clubs unrelated to major/engineering, community service, etc. 
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='established_involvement_outside',
            word_limit=500,
            prompt="""
Part of our responsibility as Triangle members is to apply what we learn here
in the &quot;outside world&quot; and, in doing so, to gain a broader
perspective. Since joining Triangle, what outside activities have you
participated in? This could include work history, research activities,
professional societies, publications/awards, mentorship/tutoring, clubs
related to engineering, clubs unrelated to major/engineering, community
service, etc.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='newmember_coe_friends',
            word_limit=500,
            prompt="""
Ean Hong was always willing to help his friends and fraternity brothers when
they needed him. Please share with us some examples from your own life, either
before or during your time at Triangle, during which you were able to help a
friend in need.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='dpan_established_coe_friends',
            word_limit=150,
            prompt="""
Daniel Summers was always willing to help his friends and fraternity brothers
when they needed him. Please share with us some examples from your time at
Triangle during which you were able to help a Triangle brother in need.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='newmember_coe_community_plans',
            word_limit=500,
            prompt="""
Ean Hong's generosity extended beyond his immediate circle of friends and
Triangle brothers. Please share with us some of your ideas on how to use your
experiences from before Triangle to assist with the fraternity's philanthropic
and community service goals.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='newmember_plans_from_others',
            word_limit=500,
            prompt="""
Triangle brothers are more than friends: we are a coalition organized around
the notion of &quot;building better men.&quot; You are new to the fraternity,
but you no doubt have been exposed to some specifics about how more senior
brothers intend to advance that goal.  Please share with us, in your own
words, a &quot;grand vision&quot; for the Penn State chapter.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='established_your_legacy_friendship',
            word_limit=500,
            prompt="""
Ean Hong was beloved by his friends, family, and fraternity brothers. In our
own way, we all leave behind a network of people whose lives were enriched by
our presence. When you leave Penn State in the future, how do you think your
fraternity brothers will remember you?
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='established_your_legacy_accomplishments',
            word_limit=500,
            prompt="""
In addition to the friendships he formed, Ean Hong left behind a legacy of
positive changes in the fraternity. When you leave Penn State, what lasting
changes will you be able to cite when speaking of your own legacy?
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='newmember_previous_leadership',
            word_limit=500,
            prompt="""
As you work and grow alongside your new fraternity brothers, you will be
drawing upon your prior achievements and challenges overcome. What leadership
opportunities have you had, and how do you think those experiences will
benefit you?
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='established_community_leadership',
            word_limit=500,
            prompt="""
A well-rounded Triangle member knows the value of the new perspectives which
come from working with people outside of his circle of friends. Please share
with us some of your accomplishments from during your time at PSU but outside
of Triangle (e.g., professional societies, clubs related or unrelated to your
major, community service, work/research activities...).
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='newmember_greek_relations_plans',
            word_limit=500,
            prompt="""
A key responsibility for any Triangle &quot;ambassador&quot; is to connect
with the larger Greek community.  As a new member, you may not have had many
opportunities in this area, but you probably have learned a little about how
the community works and how Triangle fits in. Please share some of your ideas
for enhancing our fraternity's involvement in the Greek community, based on
what you have learned from other brothers.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='newmember_greek_relations_accomplishments',
            word_limit=500,
            prompt="""
Although you are a new member, perhaps you have already begun acting as an
ambassador between Triangle and the larger Greek community. If you can, please
share your accomplishments with us. [note: answering this prompt will likely
benefit your score more than answering the alternative]
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='established_greek_relations_accomplishments',
            word_limit=500,
            prompt="""
A key responsibility for any Triangle &quot;ambassador&quot; is to connect
with the larger Greek community. Please share some of what you have
accomplished during your time at Triangle which is relevant to our goal of
furthering Greek relations.
""".strip().replace('\n', ' '))
    EssayPrompt.objects.create(
            identifier='giff_visit_review',
            word_limit=500,
            prompt="""
As a condition for the Giff Albright AE award, you should have met with a
faculty member (current or emeritus). Please give us an overview what you
learned from the faculty member and how you foresee applying that knowledge in
the future.
""".strip().replace('\n', ' '))

class Migration(migrations.Migration):

    dependencies = [
        ('freemoney', '0005_essay'),
    ]

    operations = [
        migrations.RunPython(insert_essays)
    ]
