# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerfeedbackresponse',
            name='peer_user',
        ),
        migrations.RenameField(
            model_name='additionalremarksresponse',
            old_name='response',
            new_name='full_response',
        ),
        migrations.RenameField(
            model_name='essayresponse',
            old_name='response',
            new_name='full_response',
        ),
        migrations.RenameField(
            model_name='financialaidrecord',
            old_name='response',
            new_name='full_response',
        ),
        migrations.RemoveField(
            model_name='applicantresponse',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='PeerFeedbackResponse',
        ),
    ]
